#!/bin/sh

alias ack="ack-grep"
alias steal_site="wget --mirror --convert-links --adjust-extension --page-requisites --no-parent"

#function
inotify_delay_cmd() {
  while true; do 
    inotifywait -r -e create -e delete -e modify \
      --exclude '/\..+' .
    "$@"
  done
}


alias nmapall="nmap -sP 192.168.1.0/24"
alias ll="ls -lhp"

alias trgopkg="tree $GOPATH/pkg -L 4"
alias u='du -h --max-depth=1'

alias tc_restart='sudo service tomcat7 restart'

alias vima='vim --servername a --remote-tab'

alias mytags='gcc -M *.[ch] | sed -e "s/^.*\:\s//" |\
 sed -e "s/\s\\\\$//" | sed -e "s/^ //" |\
 sed -e "s/ /\n/g" | ctags -R -L -'

# git
alias indent='sed "s/^/    /"'
alias ssweep='for f in *; do [ -d "$f/.git" ] &&\
  ( cd $f; echo "==== $(basename $PWD) [$(git_current_branch)] =====" ; git status -s 2>&2 |indent; ); done'
alias gstdirs='ssweep'
alias ggldirs="parallel $HOME/.my_linux/ggl_ ::: \$(dirname **/.git)"
alias gd='git diff'
alias grm='git rm'
alias gmv='git mv'
alias ds-gl='git log -25 --no-merges --pretty=format:"%h - %an, %ar : %s"'

# xmllint
alias xl='xmllint --noout --loaddtd --xinclude --postvalid'


# uberfast img viewer
alias thum="feh -g 640x480 -d -S filename"

alias emacsnw="emacs -nw"

# funcs

function xslt2(){
  
  if [ -z $1 ] || [ -z $2 ]; then
    echo "usage: xslt2 stylesheet src [params]" >&2 
    return 2
  fi
  
  local stylesheet=$1
  local src=$2
  shift;shift

  # TODO -Dparams as "a bulk"

  $JAVA_HOME/bin/java -cp "$SAXON" net.sf.saxon.Transform \
    -xi:on -xsl:"$stylesheet" -s:"$src" "$@"

}

function vga1max(){
xrandr --newmode "1920x1080_60.00" 148.35 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync
xrandr --addmode VGA1 1920x1080_60.00
xrandr --output VGA1 --mode 1920x1080_60.00
}

alias dc=docker-compose
