#!/bin/sh


# switch on/off da mouse


# on=1, off=0
ON_OFF=${1:-1}

#mousepad == 11
#joystick == 12
DEV_NO=${2:-11}

echo "setting dev.no $DEV_NO to $ON_OFF."

DISPLAY=:0 
xinput set-int-prop $DEV_NO "Device Enabled" 8 $ON_OFF
