#!/bin/sh

# if avail:
lxkeymap -a
# otherwise:
# setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl


while true
do
    xsetroot -name "$(date +"%F %R") /// $(acpi -b|awk 'sub(/,/,"") {print "batt:" $4}')"
    sleep 1m
done &

# kill the tocuhpad(11)
DISPLAY=:1 xinput set-int-prop 11 "Device Enabled" 8 0
# kill the clit(13)
DISPLAY=:1 xinput set-int-prop 1333Device Enabled" 8 0



exec dwm
