#!/bin/sh

# if avail:
lxkeymap -a
# otherwise:
# setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl


while true
do
    xsetroot -name "$(date +"%F %R") /// $(acpi -b|awk 'sub(/,/,"") {print "batt:" $4}')"
    sleep 1m
done &

exec dwm
