#!/bin/sh

# if avail:
lxkeymap -a
# otherwise:
# setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl


while true
do
    xsetroot -name "$(date +"%F %R") /// $(acpi -b|awk 'sub(/,/,"") {print "batt:" $4}')"
    sleep 1m
done &

export DISPLAY=:0
# kill the tocuhpad(11)
xinput set-int-prop 11 "Device Enabled" 8 0
# kill the lenovo-clit(12)
xinput set-int-prop 12 "Device Enabled" 8 0


exec dwm
