#!/usr/bin/env bash

echo -e "\n ▪ super simple automagic setup... \n"

# Makes it possible to run via curl <url>|sh
fix_this() {
  # Clone if needed
  #
  if [ ! -d ~/.my_linux/.git ]; then
    git clone git://github.com/dynnamitt/my_linux.git ~/.my_linux
  else
    echo ".my_linux clone skipped... syncing.."
    (cd ~/.my_linux && git pull)
  fi
}

CATPP_VER=v2.1.0

fix_tmux_deps() {
  mkdir -p ~/.tmux/plugins
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  mkdir -p ~/.config/tmux/plugins/catppuccin
  git clone -b $CATPP_VER https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
}

git_conf() {
  git config --global core.editor "nvim"
  git config --global user.email "kjetil.midtlie@gmail.com"
  git config --global user.name "Kjetil Midtlie"
}

pkgs() {

  if command -v apt >/dev/null; then
    sudo apt install silversearcher-ag git subversion \
      nodejs terminator python-pip zsh xsltproc
    # python
    sudo pip install --upgrade pip
    ##sudo pip install aws docker-compose
    # nodejs
    ##sudo npm i -g mocha-cli coffeescript jshint
  elif command -v pacman >/dev/null; then
    sudo pacman -S \
      yay \
      docker \
      tree \
      fzf \
      zig \
      exa \
      terminator \
      ripgrep \
      bat \
      tmux \
      neovim \
      jq \
      yamllint
    sudo yay -S \
      tfenv
  else
    echo "Not my distro(s), skipping pkgs..."
  fi

}

lazyvim() {
  git clone https://github.com/LazyVim/starter ~/.config/nvim
  rm -rf ~/.config/nvim/.git
}

fonts_() {
  find ~/sync1/fonts -iname '*tf' -printf '"%p"\n' 2>/dev/null
  find ./fonts -iname '*tf' -printf '"%p"\n' 2>/dev/null
  exit 0
}

fix_fonts() {
  sudo pacman -S $(pacman -Sgq nerd-fonts)
  # my the way:
  # FAV is :  0xProto
  # -------------
}

# ---------------------------------
#
#                main
#
# ---------------------------------
fix_this
pkgs
git_conf
fix_fonts
fix_tmux_deps
lazyvim

# tmux
ln -s ~/.my_linux/tmux.conf ~/.tmux.conf

# ctags
ln -s ~/.my_linux/_ctags ~/.ctags

# emacs
ln -s ~/.my_linux/_emacs ~/.emacs

# ghci
ln -s ~/.my_linux/ghci.conf ~/.ghci

# . ~/.my_linux/vim-pimp

# symlinking
# rm -f ~/.Xresources && ln -s ~/.my_linux/Xresources ~/.Xresources
# rm -f ~/.Xdefaults && ln -s ~/.my_linux/Xresources ~/.Xdefaults
# rm -f ~/.xinitrc && ln -s ~/.my_linux/xinitrc ~/.xinitrc
# rm -f ~/.xbindkeyrc && ln -s ~/.my_linux/xbindkeyrc ~/.xbindkeyrc
