#!/bin/sh

# replace prev vimrc
mv ~/.vimrc ~/._vimrc.backup && ln -s ~/.my_linux/vimrc ~/.vimrc 

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo " >> vim-plugs ok."
echo
echo "  run ./install to activate powerline-fonts. "
