#!/bin/sh

vim_pathogen() {
    
    echo "fetching vim-pathogen..."
    curl -Sso ~/.vim/autoload/pathogen.vim \
        https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
}

vim_plugin() {

    url=$1
    base_no_suffix=$(basename $url | sed -e 's/\.[^\.]*$//') 
    _dirname_=${3:-${base_no_suffix}}
   
    printf "\n\n  --- $_dirname_ --- \n"
    printf "fetching vim plugin: $url\n" 
    cvs=${2:-git}
    cvs_sync=pull
    cvs_clone=clone
    
    if test $cvs = svn
    then
        cvs_sync=update
        cvs_clone=checkout
    fi

    (
    cd $HOME/.vim/bundle
    if test -f "$_dirname_/.git/index" || test -d "$_dirname_/.svn" 
    then
        echo " >> sync.."
        (
        cd $_dirname_
        $cvs $cvs_sync
        )
    else
        echo " >> clone/checkout.."
        $cvs $cvs_clone $url $_dirname_
    fi
    )
}
