#!/bin/sh

dmenu_run -fn "-*-fixed-*-r-*-*-*-150-*-*-*-*-iso10646-*" -nb "#444" -nf "#eee"

# cutt n paste
autocutsel &

# background
feh --bg-center ~/sync1/graphic/evil_dead_regeneration_01_1680x1050.jpg

